version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser
    user: "1000:1000"
    ports:
      - "9600:80"
    volumes:
      - /home/pi:/srv
      - /home/pi/services/filebrowser/filebrowser.db:/database.db
      - /home/pi/services/filebrowser/.filebrowser.json:/.filebrowser.json

    restart: unless-stopped

